// Code generated by MockGen. DO NOT EDIT.
// Source: dataaccess.go

// Package mock is a generated GoMock package.
package mock

import (
	models "enterpret/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDataStore is a mock of DataStore interface.
type MockDataStore struct {
	ctrl     *gomock.Controller
	recorder *MockDataStoreMockRecorder
}

// MockDataStoreMockRecorder is the mock recorder for MockDataStore.
type MockDataStoreMockRecorder struct {
	mock *MockDataStore
}

// NewMockDataStore creates a new mock instance.
func NewMockDataStore(ctrl *gomock.Controller) *MockDataStore {
	mock := &MockDataStore{ctrl: ctrl}
	mock.recorder = &MockDataStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataStore) EXPECT() *MockDataStoreMockRecorder {
	return m.recorder
}

// FeedbackCount mocks base method.
func (m *MockDataStore) FeedbackCount(tenant, source string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FeedbackCount", tenant, source)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FeedbackCount indicates an expected call of FeedbackCount.
func (mr *MockDataStoreMockRecorder) FeedbackCount(tenant, source interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FeedbackCount", reflect.TypeOf((*MockDataStore)(nil).FeedbackCount), tenant, source)
}

// FetchFeedbacks mocks base method.
func (m *MockDataStore) FetchFeedbacks(tenant string, page, size int, source ...string) ([]models.FeedbackIngest, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{tenant, page, size}
	for _, a := range source {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FetchFeedbacks", varargs...)
	ret0, _ := ret[0].([]models.FeedbackIngest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchFeedbacks indicates an expected call of FetchFeedbacks.
func (mr *MockDataStoreMockRecorder) FetchFeedbacks(tenant, page, size interface{}, source ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{tenant, page, size}, source...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchFeedbacks", reflect.TypeOf((*MockDataStore)(nil).FetchFeedbacks), varargs...)
}

// Store mocks base method.
func (m *MockDataStore) Store(ingest models.FeedbackIngest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ingest)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockDataStoreMockRecorder) Store(ingest interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockDataStore)(nil).Store), ingest)
}
